---
title: "About us"
format: html 
---
<p>
**Nina Jobanputra** is a senior engineering major at Harvey Mudd College. She is interested 
in working as an electrical engineer in biotech fields, or robotics. In her free 
time you can find Nina on the Ultimate Field or in Rock Creek, Washington DC. Find her on 
[LinkedIn](https://www.linkedin.com/in/nina-jobanputra/) or check out her [portfolio](https://njobanputra.github.io/hmc-e155-portfolio/).
</p>
<p>
**Emily Kendrick** is also a senior engineering major at Harvey Mudd. She doesn't really know 
exactly what she wants to do with her life, but is interested in lots of things EE. When she is not
doing schoolwork she is definitely running. She has lived in southern California her whole life. Find 
her on [LinkedIn](https://www.linkedin.com/in/emily56/) or check out her [portfolio](https://emenemi1y.github.io/HMC-E155-PORTFOLIO/).
</p>

## Acknowledgements
We would like to thank Prof Spencer and Kavi for their help in progressing through this project. 
We would also like to thank Jacob in the stockroom for helping us find the 
parts we needed.

